---
- name: Run Repository Deployment Tasks
  ansible.builtin.include_tasks: repository.yml

- name: Run Environment Configuration Tasks
  ansible.builtin.include_tasks: env.yml

- name: Run Docker Deployment Tasks
  ansible.builtin.include_tasks: deploy.yml

- name: Flush handlers to execute service restarts before health checks
  ansible.builtin.meta: flush_handlers

- name: Run Health Verification Tasks
  ansible.builtin.include_tasks: health.yml
...
